- azure-pipelines.yml
- setup.cake
Enable integration tests on Azure Pipelines
> Enable integration tests on Azure Pipelines

- src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs
> (GH-17) Improve logging

- src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs
Check files even if there are only binary files in the repository
Fixes #18
> (GH-18) Check files even if there are only binary files in the repository

- src/Cake.Issues.GitRepository/GitRepositoryIssuesAliases.cs
- src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs
Make issue provider type name available on issue provider
Fixes #30
> (GH-30) Make issue provider type name available on issue provider

- src/Cake.Issues.GitRepository.Tests/IssueBuilderExtensionsTests.cs
- src/Cake.Issues.GitRepository/BaseGitRepositoryIssuesRuleDescription.cs
- src/Cake.Issues.GitRepository/BinaryFileNotTrackedByLfsRuleDescription.cs
- src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs
- src/Cake.Issues.GitRepository/IssueBuilderExtensions.cs
Provide metadata about rules which are checked by the issue provider
Fixes #29
> (GH-29) Provide metadata about rules

- src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs
Improve performance by caching data which requires access to Git
> Improve performance by caching access to Git

- docs/rules/BinaryFileNotTrackedByLfs.md
- docs/rules/FilePathTooLong.md
Add information in which version a rule is available
Fixes #44
> (GH-44) Add information in which version a rule is available

- docs/features.md
Add FilePathTooLong rule to feature list
> Add FilePathTooLong rule to feature list

- src/Cake.Issues.GitRepository.Tests/Cake.Issues.GitRepository.Tests.csproj
- src/Cake.Issues.GitRepository/Cake.Issues.GitRepository.csproj
- src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs
- tests/integration/tests.cake
Update Cake.Issues to 0.8.0
Fixes #41
> (GH-41) Update Cake.Issues to 0.8.0

- docs/features.md
- src/Cake.Issues.GitRepository.Tests/Cake.Issues.GitRepository.Tests.csproj
- src/Cake.Issues.GitRepository/Cake.Issues.GitRepository.csproj
Updates to Cake.Issues 0.9.0
Fixes #75
> (GH-75) Update to Cake.Issues 0.9.0

- src/Cake.Issues.GitRepository.Tests/Cake.Issues.GitRepository.Tests.csproj
- src/Cake.Issues.GitRepository/Cake.Issues.GitRepository.csproj
Build against Cake.Issues 1.0.0 Beta 1
Fixes #106
> (GH-106) Build against Cake.Issues 1.0.0 Beta 1

- src/Cake.Issues.GitRepository/Cake.Issues.GitRepository.csproj
Migrate from FxCop analyzers to NETAnalyzers
Fixes #100
> (GH-100) Migrate from FxCop analyzers to NETAnalyzers

- recipe.cake
Ignore DiffEngine and EmptyFiles for coverage
> Ignore DiffEngine and EmptyFiles for coverage

- recipe.cake
Disable Coveralls since it is currently failing
> Disable Coveralls

- src/Cake.Issues.GitRepository.Tests/Cake.Issues.GitRepository.Tests.csproj
- src/Cake.Issues.GitRepository.Tests/IssueBuilderExtensionsTests.cs
- src/Cake.Issues.GitRepository/BaseGitRepositoryIssuesRuleDescription.cs
- src/Cake.Issues.GitRepository/BinaryFileNotTrackedByLfsRuleDescription.cs
- src/Cake.Issues.GitRepository/Cake.Issues.GitRepository.csproj
- src/Cake.Issues.GitRepository/FilePathTooLongRuleDescription.cs
- src/Cake.Issues.GitRepository/IssueBuilderExtensions.cs
Builds against Cake 2.0
Fixes #126
> (GH-126) Build against Cake 2.0

- .github/dependabot.yml
Ignore Cake 2.x updates in Dependabot
> Ignore Cake 2.x updates in Dependabot

- azure-pipelines.yml
Add tests against Ubuntu 22 and remove tests against Ubuntu 18
> Test against Ubuntu 22

- .vscode/settings.json
Adds configuration for Visual Studio Code C# extension
> Add Visual Studio Code configuration

- .appveyor.yml
- azure-pipelines.yml
- nuspec/nuget/Cake.Issues.GitRepository.nuspec
- src/Cake.Issues.GitRepository.Tests/GitRunnerFixture.cs
- src/Cake.Issues.GitRepository/Cake.Issues.GitRepository.csproj
- src/Cake.Issues.GitRepository/GitRepositoryIssuesProvider.cs
- src/Cake.Issues.GitRepository/GitRunner.cs
- src/Cake.Issues.GitRepository/GitRunnerSettings.cs
- src/Directory.Build.props
Multi-Target .NET 6, .NET 7 & .NET 8
Fixes #197
> Multi-Target .NET 6, .NET 7 & .NET 8

- src/Cake.Issues.GitRepository.Tests/Cake.Issues.GitRepository.Tests.csproj
- src/Cake.Issues.GitRepository/Cake.Issues.GitRepository.csproj
Build against Cake Issues 4.0.0-beta0001
Fixes #199
> Build against Cake Issues 4.0.0-beta0001

- global.json
- tests/script-runner/global.json
> Add global.json
